### PR TITLE
Initial support for the US version of the TX Ultimate

### PR DESCRIPTION
**Pull request by ShonP40**
Basically modified the LED config, so the 4-gang switch still isn't going to work properly (will try to fix that later)

Also, I recommend applying a 0.7s transition to LED effects to make them look smoother (did it for the US version).

### CODE REVIEW

**Comment by ShonP40** [comment]
Added a double covers config file for 4-gang US switches as well
(Haven’t tested it yet, going to later today or tomorrow)

**Comment by ShonP40** [comment]
Also added a config for one cover and two switches

**Comment by ShonP40** [comment]
Kinda forgot to update the normal & local config files to include support for the 4-gang version so I’ll do it later today probably

**Comment by Orzionab** [comment]
> Kinda forgot to update the normal & local config files to include support for the 4-gang version so I’ll do it later today probably

Hi, can you upload here? 
I have a 4 gang us and still not working for me

**Comment by ShonP40** [comment]
I’ll make a new PR for it in a few minutes

**Comment by ShonP40** [comment]
> > Kinda forgot to update the normal & local config files to include support for the 4-gang version so I’ll do it later today probably
> 
> Hi, can you upload here? I have a 4 gang us and still not working for me

https://github.com/SmartHome-yourself/sonoff-tx-ultimate-for-esphome/pull/30

**Comment by ShonP40** [comment]
It’s been merged into the main repo

**Comment by danielscheidler** [comment]
Pr accepted

Shon ***@***.***> schrieb am Do., 15. Feb. 2024, 09:12:

**Comment by TommySharpNZ** [comment]
Thanks for this! I have been holding out for someone with more skill than myself to get the US version working!!!

**Pull request merged**
